name:                relayeet
version:             0.1.0.0
github:              "konn/relayeet"
license:             BSD3
author:              "Hiromi ISHII"
maintainer:          "konn.jinro _at_ gmail.com"
copyright:           "2018 (c) Hiromi ISHII"

extra-source-files:
- README.md
- ChangeLog.md

ghc-options:
-  -Wall

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/konn/relayeet#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - aeson
  - SHA
  - base64-bytestring
  - bytestring
  - http-api-data
  - http-types
  - mtl
  - pwstore-fast
  - servant
  - servant-server
  - text
  - twitter-types
  - vcache
  - wai
  - yaml

executables:
  relayeet-server:
    main:                server.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - aeson
    - async
    - bytestring
    - http-types
    - mtl
    - pwstore-fast
    - relayeet
    - servant
    - servant-server
    - stm
    - text
    - wai
    - warp

  relayeet-client:
    main:                client.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - aeson
    - bytestring
    - conduit
    - http-conduit
    - http-types
    - lens
    - relayeet
    - shelly
    - text

  relayeet-issue-token:
    main:                issue-token.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - nonce
    - pwstore-fast
    - relayeet
    - vcache

  relayeet-mock-streamer:
    buildable:           false
    main:                mock-streamer.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - aeson
    - http-client
    - relayeet
    - servant-client
    - text

  relayeet-register-endpoint:
    main:                register-endpoint.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aeson
    - async
    - authenticate-oauth
    - bytestring
    - hashable
    - http-client
    - http-client-tls
    - http-types
    - lens
    - mtl
    - relayeet
    - servant
    - servant-server
    - stm
    - stm-containers
    - text
    - warp
    - wreq
