name:                relayeet
version:             0.1.0.0
github:              "konn/relayeet"
license:             BSD3
author:              "Hiromi ISHII"
maintainer:          "konn.jinro _at_ gmail.com"
copyright:           "2018 (c) Hiromi ISHII"

extra-source-files:
- README.md
- ChangeLog.md

ghc-options:
-  -Wall

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/konn/relayeet#readme>

dependencies:
- aeson
- acid-state
- base >= 4.7 && < 5
- unordered-containers
- bytestring
- base64-bytestring
- http-api-data
- SHA
- exceptions
- mtl
- conduit
- wai
- warp
- text
- servant
- servant-auth
- stm
- stm-chans
- http-types
- wreq
- lens

library:
  source-dirs: src
  dependencies:
  - yaml
  - safecopy
  - transformers
  - http-types

executables:
  relayeet-server:
    main:                server.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - relayeet
    - servant
    - servant-auth-server
    - servant-server

  relayeet-client:
    main:                client.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - relayeet
    - servant-client
    - servant-auth-client

  relayeet-mock-streamer:
    buildable:           false
    main:                mock-streamer.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - relayeet
    - servant-client
    - http-client
    - servant

  relayeet-register-endpoint:
    main:                register-endpoint.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - relayeet
    - servant-client
    - http-client
    - http-client-tls
    - authenticate-oauth
    - servant
    - servant-server
    - wreq
    - servant
    - stm-containers
    - async
    - wai
    - warp
    - hashable
