resolver: lts-14.14
packages:
- .

extra-deps: 
- pwstore-fast-2.4.4 
- stm-containers-1.1.0.4
- twitter-types-0.9.0
- vcache-0.2.6
- direct-murmur-hash-1.0.1
- stm-hamt-1.2.0.4
- primitive-0.7.0.0
- primitive-extras-0.8
- primitive-unlifted-0.1.2.0
# - direct-murmur-hash-1.0.1
# - pwstore-fast-2.4.4
# - twitter-types-0.7.2.2
# - vcache-0.2.6
